### ISSUE TITLE
Cmd+S in macOS adds a new line at the end

### ISSUE THREAD

**Issue by onewildgamer** [foambubble/foam-vscode#10]
Pressing Cmd+S in the VS Code after installing the extension adds a new line at the end of the file.

[Screen Recording 2020-06-28 at 22.07.07.mov.zip](https://github.com/foambubble/foam-vscode/files/4842645/Screen.Recording.2020-06-28.at.22.07.07.mov.zip)

**Comment by jevakallio** [comment]
Thanks for reporting! This is related to #3 and #5 and possibly addressed by PR #6. 

I'm looking to get this fixed ASAP, but will need to setup a Windows environment for testing to ensure we don't break it on different platforms / edge cases.

**Comment by Georift** [comment]
@jevakallio ~~I have a Windows environment with this issue visible if you'd like me to test a branch.~~

Seen the PR. I'll give it a try now.

**Comment by YashKumarVerma** [comment]
Update: facing the same issue on Ubuntu 19.04 (`ctrl`+`s` adds a new line)

**Comment by jevakallio** [comment]
Thanks for reporting this! Fixed in [v0.1.5](https://github.com/foambubble/foam-vscode/releases/tag/v0.1.5), available in Marketplace.

Closing issue now, let me know if it still persists after the version update and we'll reopen. Remember to reload the VS Code window after updating the extension!
