### ISSUE TITLE
Support for code-server (VSCode 1.45.1)

### ISSUE THREAD

**Issue by ariez-xyz** [foambubble/foam-vscode#12]
I've been trying to get Foam to work with [code-server](https://github.com/cdr/code-server) on my iPad. code-server is currently on VS Code 1.45.1 due to a [bug](https://github.com/cdr/code-server/pull/1672). Would it be feasible for Foam to add support for VS Code 1.45.1?

**Comment by jevakallio** [comment]
@AriezLabs possibly, but it's not a high priority at the moment, and given how much of Foam is actually implemented in our [recommended extensions](https://foambubble.github.io/foam/recommended-extensions), adding legacy support to all those libraries could be a large undertaking.

If you can help me figure out what would need to be changed, I'd be open to considering it.

**Comment by jevakallio** [comment]
@AriezLabs I've just discovered this is just a `engine` field setting in package.json, and we were not actually relying on any 1.46.0 features.

I've released [0.1.6](https://github.com/foambubble/foam-vscode/releases/tag/v0.1.6) with support for this version. Could you test it out and let me know if it works?

For some reason I was under the impression that 1.45.1 was far older vintage, not the previous minor. Apologies.
