### ISSUE TITLE
AsciiDoc support

### ISSUE THREAD

**Issue by ryansharif** [foambubble/foam-vscode#14]
It would be nice if we could support Markdown's older sibling, AsciiDoc. I'll have a look at what it would take to support such a change.

**Comment by jevakallio** [comment]
@ryansharif in it's current implementation, Foam is largely used in conjunction with our other [recommended extensions](https://foambubble.github.io/foam/recommended-extensions), and Markdown+Wikilinks is the interoperability format for all these documents.

So while we could support AsciiDoc in the foam-vscode extension, that would break Foam's third party support. In a distant hypothetical future Foam might bring these functionalities "in-house" at which point we could explore other format support, but for the time being it's not on the roadmap.

If you want to use something Foam-like for AsciiDoc documents, I recommend forking Foam and finding/building extensions that achieve the same for AsciiDoc.

Good luck!
