### ISSUE TITLE
Support relative links between directories

### ISSUE THREAD

**Issue by jevakallio** [foambubble/foam-vscode#8]
As discussed with @JordiCorbilla [on Twitter](https://twitter.com/thunderjordi/status/1276786509279105027)

<img width="1326" alt="Screenshot 2020-06-27 at 10 05 10" src="https://user-images.githubusercontent.com/1203949/85919100-4ad3ff00-b860-11ea-8d3c-323dbe29f60b.png">

**Comment by stevemoser** [comment]
Non-mediawiki style links could also fix this issue, link from related issue: https://github.com/foambubble/foam/issues/16#issuecomment-652517625
